### ISSUE TITLE
offtopic: would transparency be also possible with the 'alltalk icon'?

### ISSUE THREAD

**Issue by fred0r** [UnrealKaraulov/GOD-SEEKER-CS16#2]
this isnt about adding this feature to this particular plugin, but since you hide the whole player model with this plugin:
would it be possible to use the same 'technique' to hide the 'alltalk icon' when alltalk is enabled on the server?

**Comment by UnrealKaraulov** [comment]
@fred0r it can be fixed in 3.0 (disable player speak when invisible)

**Comment by fred0r** [comment]
thx - but itried to ask for - since you are able to hide player models:
would it be also possible for you to create some plugin which blocks the 'alltalk'-symbol to ALL players on the server, when sv_alltalk is enabled?

**Comment by UnrealKaraulov** [comment]
> thx - but itried to ask for - since you are able to hide player models: would it be also possible for you to create some plugin which blocks the 'alltalk'-symbol to ALL players on the server, when sv_alltalk is enabled?

I don't know how to do it((((
